name: Unpublish Test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 22 * * *' #  run at 5:10PM for Americas and Europe
    - cron:  '10 8 * * *' # run at 5:10PM for APAC
  workflow_dispatch:

jobs:
  unpublish:
    environment:
      name: main
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Run this every 15 minutes"
      - name: Set APAC Timezone Variable
        id: set-region
        if: github.event.schedule == '10 8 * * *'
        run: echo "region='APAC'" >> "$GITHUB_OUTPUT"
      - name: Set AMER Timezone Variable
        id: set-region
        if: github.event.schedule == '5 22 * * *'
        run: echo "region='AMER'" >> "$GITHUB_OUTPUT"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Script
        id: unpublish-script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const { default: unpublishPastEvents } = await import('${{ github.workspace }}/scripts/unpublish-pages.mjs')
            console.log('${{ github.event.schedule }}')
            console.log('${{ steps.set-region.outputs.region }}')

            const response = await unpublishPastEvents(process.env.AUTH_TOKEN)
            console.log(response)
            core.setOutput("subject", response.subject)
            core.setOutput("body", response.body)
            return response
          result-encoding: string
      - name: Send Email Notifications
        uses: cinotify/github-action@main
        with:
          to: 'laurel.timko@jmp.com'
          subject: "${{steps.unpublish-script.outputs.subject}}"
          body: "${{steps.unpublish-script.outputs.body}}"
          type: 'text/html'
