name: Unpublish Test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,15,30,45 * * * *'

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Run this every 15 minutes"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Script
        uses: actions/github-script@v7
        with:
          script: |
            console.log('hello world')
            const { default: printStuff } = await import('${{ github.workspace }}/scripts/unpublish-pages.mjs')

            await printStuff('my value')
