name: Unpublish Test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 21 * * *'
  workflow_dispatch:

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Run this every 15 minutes"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Script
        env:
          AUTH_TOKEN: ${{ secrets.AUTHORINGAUTHTOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            console.log('${{ secrets.AUTHORINGAUTHTOKEN }}')
            const { default: printStuff } = await import('${{ github.workspace }}/scripts/unpublish-pages.mjs')

            await printStuff('$AUTH_TOKEN')
