name: Unpublish Test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 21 * * *'
  workflow_dispatch:

jobs:
  unpublish:
    environment:
      name: main
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Run this every 15 minutes"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Script
        id: unpublish-script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const { default: unpublishPastEvents } = await import('${{ github.workspace }}/scripts/unpublish-pages.mjs')

            const response = await unpublishPastEvents(process.env.AUTH_TOKEN)
            console.log(response)
            return response
          result-encoding: string
      - name: Generate Email
        id: email-prop
        run: >
          IFS=- read -r failedNum bodyText <<< ${{steps.unpublish-script.outputs.result}}
          if [ ((failedNum)) -gt 0 ]; then
            echo "subject='Failed to unpublish pages'" >> "$GITHUB_OUTPUT"
          else
            echo "subject='Successfully unpublished pages'" >> "$GITHUB_OUTPUT"
          fi
          echo "body=$bodyText" >> "$GITHUB_OUTPUT"
      - name: Send Email Notifications
        uses: cinotify/github-action@main
        with:
          to: 'laurel.timko@jmp.com'
          subject: "Result ${{steps.email-prop.outputs.subject}}"
          body: "Body ${{steps.email-prop.outputs.body}}"
          type: 'text/html'
